### ISSUE TITLE
css: 背景图位置设定

### ISSUE THREAD

**Issue by SuAutumn** [SuAutumn/somethine_about_work#2]
```css
selector {
  background-position: x y; /* 背景图相对原点的位移，可选：center left 之类，也可以具体设置长度，当设置多个img的位置时候，使用‘,’间隔 */
  background-origin: padding-box; /* position位置相对原点，默认padding-box，可选：border-box, content-box; */
}
```
